version: '3.8'

services:
  rename-eraser-files:
    build: .
    container_name: rename-eraser-files
    ports:
      - "5000:5000"
    volumes:
      # CAMBIA la parte izquierda por la ruta a la carpeta de tu ordenador que contiene los videos.
      # Ejemplo en Windows: - C:\Users\Usuario\Videos:/data
      # Ejemplo en Linux/Mac: - /home/usuario/videos:/data
      - C:\Users\Usuario\Videos:/data
    restart: unless-stopped
